### ISSUE TITLE
Very useful utility

### ISSUE THREAD

**Issue by clanmills** [pyke369/isobmffdump#1]
Hi Pierre Yves:

I'm the Lead Engineer for Exiv2 (http://exiv2.org and https://github.com/exiv2/exiv2).  I received a request on Friday to support ISO BMFF Files (and Canon's new CR3 Format).  I'm investigating existing code and really like the simplicity of isobmffdump.  I'm wondering if you'd like to join Team Exiv2 and undertake the support of ISO BMFF.  I'll help and mentor you.

Exiv2 is a C++ Metadata Library.  It is installed on most Linux distros and is used by many open-source applications such as GIMP, digiKam, GwenView and many others.  It's also used by the gnome desktop tools such as Dolphin and Konqueror.

Exiv2 is a cross platform library and we support 18 platforms including Linux, MacOS-X, Cygwin and all versions of MSVC back to 2005.

Here's are the request received on Friday:  https://github.com/Exiv2/exiv2/issues/235

**Comment by pyke369** [comment]
Hello Robin, sure, I'd be happy to. That being said, this tool is very simple (as you said) and should not require a lot of maintenance efforts.

**Comment by clanmills** [comment]
Thanks for the reply.  I was wondering if I could recruit you to Team Exiv2.  Your code is a good starting point to include CR3 support into Exiv2 and there are engineers from darktable and the community participating.  Exiv2 is a C++ Metadata Library and used by Gimp, darktable, GwenView and many other applications.

As you are interested in ISO BMFF, I'm inviting you to join the community and bring CR3 support to the world.  However, if you'd prefer to not get involved, that's totally OK.  I appreciate your code and the courtesy of your reply.  Best Wishes.
